### ISSUE TITLE
Potential sync issue in the multi-MFLI setup in the latest firmware (could also be the driver)

### ISSUE THREAD

**Issue by FarBo** [zhinst/zhinst-qcodes#24]
Dear ZI,

We recently got report from our labs that with the latest qcodes and toolkit driver 0.2.x, there are random phase change in the two-MFLI setup. So, we think that there is some kind of a sync problem. 
As we didn't have this problem report with the older driver (sync was more stable), we tried multiple tests to provide you with the minimal attached example notebook:
[ZI MDS sync issue.zip](https://github.com/zhinst/zhinst-qcodes/files/7505717/ZI.MDS.sync.issue.zip)

We tried to describe our findings in the notebook, but feel free to ask any question if something is not clear in the notebook.

For now, we limited zi drivers to 0.1.x, and asked our users to not update to the latest firmware.

Thank you.

**Comment by tobiasah** [comment]
Sry to hear that you have this kind of problems with the latest version.
We will take a look into it as soon as possible and keep you updated here.

**Comment by tobiasah** [comment]
We looked into the notebook file and I think the reason for the random phase change is not the newer firmware but a small bug in your code. The reason why it seems to work better with older versions is probably just random or at least we could not spot a difference in our measurements. 

▶️  Maybe at the beginning the polar plot generated with an improved version of your notebook file and the latest firmware/drivers. Easy to spot is the stable phase.
![polar_plot](https://user-images.githubusercontent.com/73690588/141431284-4a465f4f-3c22-4c05-8abf-02aa00a698c2.png)

But let me quickly summarize our findings:
Inside the measurement loop you call `setup_mds` before every measurement. Since the  `setup_mds` instantiates a new session to the server and sets up a new mds module the measurements as a whole is not synchronized correctly (in addition to the performance decrease and potential problems of the mds module since it is destroyed at the end of the setup_mds method).

The right way to do it would be setup the mds before the measurement and only sync the phases inside the loop (`mds.set("phasesync", 1)`).

In your example this would look something like the following (⚠️ marking stuff that differs from you version):

* the setup function
```
# ⚠️ the daq instance must survive at least as long as the mds instance
def setup_mds(daq):
    #MDS setup
    name_list = ["DEV" + mfli.features.serial() for mfli in (mfli1, mfli2)]
    devices = ",".join(name_list)
    mds = daq.multiDeviceSyncModule()
    mds.set("start", 0)
    mds.set("group", 0)
    # ⚠️ recover is not necessary during startup
    #mds.set("recover", 1)
    mds.execute()
    mds.set("devices", devices)
    mds.set("start", 1)
    # ⚠️ execute is not necessary because it was invoked earlier
    #mds.execute()
    print(mds.getString("message"))
    timeout = 20
    start = time.time()
    status = 0
    while status != 2:
        time.sleep(0.5)
        status = mds.getInt("status")
        if status == -1:
            raise Exception("error during device sync")
        else:
            print(f"status {status}")
        if (time.time() - start) > timeout:
            raise Exception("timeout")
    print(mds.getString("message"))
    print("devices synced")

    #⚠️ phasesync will be executed in the loop
    #mds.set("phasesync", 1)
    return mds
```
* the measurement loop
```
#⚠️ create daq session outside of the setup function
apilevel = 6
port = 8004
daq = zhinst.ziPython.ziDAQServer("localhost", api_level=apilevel, port=port)
#⚠️ keep the reference to the mds module 
mds = setup_mds(daq)
freqs = np.linspace(10,1e3, 10)
data = []
for freq in freqs:
    # Set the frequency of instruments
    mfli1.oscs[0].freq(freq)
    mfli2.oscs[0].freq(freq)
    # ⚠️ Perform only oscillators phase synchronization 
    mds.set("phasesync", 1)
    time.sleep(2.0)
    data.append(mfli2.demods[0].sample())
```
* cleaning up after the measurement 
```
mds.set("start", 0)
mds.finish()
mds.clear()
```

I have attached a modified version of your notebook so that you can test it out yourself. 
We hope that you now can use the latest firmware and drivers with no issues.

If you still encounter other problems, have follow up question or this issue even remains feel free to comment it here and we will try solving it together or get the assistance of one of you application scientists. 

[zi_mds_sync_proposal.ipynb.zip](https://github.com/zhinst/zhinst-qcodes/files/7525993/zi_mds_sync_proposal.ipynb.zip)

**Comment by FarBo** [comment]
@tobiasah 

Greatly appreciate your effort and time on this matter. Basically, we tried to mimic mds from the API log in the LabOne interface, so we were also not sure our implementation was completely correct because we could not find an API documentation to implement it in a more solid way. However, with the old driver and firmware, we got a reasonable sync between MFLIs. Therefore, our first speculation was that there might be something changed in the driver/ firmare that does not like our mds.

We hope your suggestions to fix the mentioned problem in our side as well, then we can upgrade to the latest firmware and driver in our labs.
We will arrange a test ASAP, and update its result here.

**Comment by jenshnielsen** [comment]
@tobiasah Thanks, further to what Farzad noted we had the issue that any attempts at returning an initialized mds module resulted in 

```RuntimeError: Main ziPython interface was removed. Calls to module are illegal.```

When trying to do any operation on the returned mds module. 

From looking at your code it is not completely clear why we were seeing that issue and you were not. 
And that is the reason why the code that this example is based on redoes the whole syncing each time. 
Looking at your code the only difference that I can see is the you do not call `phasesync` before returning the mds module. 
(We have tried various versions with and without the use of recover and execute and so on which are not shown here with the same result). Do you have any insight into why we are seeing that error?

**Comment by tobiasah** [comment]
@jenshnielsen thanks for the follow up question.

Short answer: The mds module is part of  needs an active session (`zhinst.ziPython.ziDAQServer`) and can not live by its own. 

Longer one 😁 :
the reason for the error you mentioned was that you have instantiated the session to the Date Server (`zhinst.ziPython.ziDAQServer`) inside the `setup_mds` method. Inside the method you have used that session the create the instance of a mds module. 
Since `setup_mds` only returns the mds instance the daq object will be destroyed at the end of the method and with it the session to the DataSever that the mds module relies on, making it useless.

In our solution we instantiate the session outside of `setup_mds` and pass it as an argument to `setup_mds`. Another option would be to return a pair of the daq and mds object in `setup_mds` ... 

One conclusion we draw (and already have worked on) is that we need to improve and extend our documentation a lot. So hopefully you don't encounter these kind of troubles again.

**Comment by jenshnielsen** [comment]
@tobiasah Thanks that sounds very reasonable. We will test your example and adapt our code if that solves the issue. Looking forward to improved documentation.

**Comment by FarBo** [comment]
@tobiasah 
We have tried your proposal and seems for this minimal notebook, it significantly improved the mds. 
So thanks again :)
