### ISSUE TITLE
Session based instrument factory produces instruments of unexpected type

### ISSUE THREAD

**Issue by jenshnielsen** [zhinst/zhinst-qcodes#40]
Consider the difference between creating an MFLI via the session object and manually.

```python
from zhinst.qcodes import ZISession
from zhinst.qcodes import MFLI

session = ZISession("localhost")
session.connect_device('dev4493')
mfli = session.devices['dev4493']

isinstance(mfli, MFLI)
False

mfli.close()
mfli = MFLI(name="mfli1", serial="dev4493", host="localhost")
isinstance(mfli, MFLI)
True
mfli.close()
```

The instrument produced by the session api is of type ZIBaseInstrument and not MFLI as expected 

## Versions:

```
zhinst                   22.2.29711
zhinst-deviceutils       0.1
zhinst-qcodes            0.3.4
zhinst-toolkit           0.3.3
```

In general I find the session based api suboptimal to use with QCoDeS since

* Instruments cannot easily be setup using a yaml definition which is standard for QCoDeS
* Its no longer possible to subclass instruments for customization

**Comment by tobiasah** [comment]
@jenshnielsen thanks for this issue. This is one of the major challenges we had during the development of this driver. I hope I can summarize it in an understandable way. 

We know that QCoDeS connections are device based. On the other hand all Zurich Instrument devices are Session based. In the old driver the conversion between theses designs where done in toolkit. But this is no longer the case, since toolkit should be a universal high level abstraction layer. Thus we need to do the conversion in QCoDeS. 

We designed the package interface in such a way that customers normally don't have to worry about sessions and can simple use the exposed device classes. This is the intended way to use our drivers.

```
from zhinst.qcodes import MFLI 
device = MFLI("dev1234","localhost")
```
One can also derive from this class if needed without any restrictions.

However we also exposed the `ZISession` class, since we are aware of customers who would like to take the full potential of the Session based approach and therefor need full control over the creation and management of the session. 

I agree we did make a mistake to highlight the session in the documentation instead of the device based approach and that we must change as part of this issue. 

So in short it is not advised to use both the Session based approach and the device based approach within one experiment. 

------------------------------------

The explanation why the two created objects are not the same is fairly simple. The exposed `MFLI` class is only a stub class deriving from `ZIBaseInstrument`. The only difference between these two is the different `init` function. The `MFLI` stub overwrites it and creates a Session (if necessary) itself (https://github.com/zhinst/zhinst-qcodes/blob/b403bf0963fd011be14250a75bc897b5835ecc4c/src/zhinst/qcodes/device_creator.py#L56) where the `ZIBaseInstrument` requires and existing Session that it does not own (https://github.com/zhinst/zhinst-qcodes/blob/b403bf0963fd011be14250a75bc897b5835ecc4c/src/zhinst/qcodes/driver/devices/base.py#L11).

So if one slightly adapt your example one gets: 

```
from zhinst.qcodes import MFLI, ZISession

session = ZISession("localhost")
mfli_1 = session.connect_device("dev1234")
mfli_2 = MFLI("dev1234", "localhost", name="mfli_2")
isinstance(mfli_2,type(mfli_1))
True
```
------------------------------------
To conclude we will adopt your documentation to focus on the Device base approach. But we don`t see any action points for our code. Or do you disagree?
